name: rickmodular
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.10
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  http: ^1.2.1
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
